from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

from git_ai.config import SUPPORTED_LANGUAGES, SUPPORTED_PROVIDERS

DEFAULT_OUTPUT = Path("git-ai.yaml")
DEFAULT_PROVIDER = "ollama"
DEFAULT_MODEL = "llama3.1:8b"
DEFAULT_LANGUAGE = "en"
DEFAULT_BASE_URL = "http://localhost:11434"
DEFAULT_PUSH_AFTER_COMMIT = False
DEFAULT_REMOTE = "origin"
DEFAULT_COMMIT_FORMAT = "conventional"
DEFAULT_MAX_SUBJECT_LENGTH = 72
DEFAULT_INCLUDE_BODY = False


def _validate_language(lang: str) -> str:
    normalized = lang.strip().lower()
    if normalized not in SUPPORTED_LANGUAGES:
        supported = ", ".join(sorted(SUPPORTED_LANGUAGES))
        raise typer.BadParameter(
            f"Unsupported language: '{lang}'. Supported languages: {supported}."
        )
    return normalized


def _validate_provider(provider: str) -> str:
    normalized = provider.strip().lower()
    if normalized not in SUPPORTED_PROVIDERS:
        supported = ", ".join(sorted(SUPPORTED_PROVIDERS))
        raise typer.BadParameter(
            f"Unsupported provider: '{provider}'. Supported providers: {supported}."
        )
    return normalized


def _validate_non_empty(value: str, field_name: str) -> str:
    normalized = value.strip()
    if not normalized:
        raise typer.BadParameter(f"{field_name} ne peut pas être vide.")
    return normalized


def _build_init_config_text(
    *,
    provider: str,
    model: str,
    language: str,
    base_url: str,
    push_after_commit: bool,
) -> str:
    push_value = "true" if push_after_commit else "false"
    include_body_value = "true" if DEFAULT_INCLUDE_BODY else "false"

    return (
        "# Git AI configuration\n"
        "# Generated by: git-ai init\n"
        "\n"
        f"provider: {provider}\n"
        f"model: {model}\n"
        f"language: {language}\n"
        f"base_url: {base_url}\n"
        "\n"
        "commit:\n"
        f"  format: {DEFAULT_COMMIT_FORMAT}\n"
        f"  max_subject_length: {DEFAULT_MAX_SUBJECT_LENGTH}\n"
        f"  include_body: {include_body_value}\n"
        "\n"
        "git:\n"
        f"  push_after_commit: {push_value}\n"
        f"  remote: {DEFAULT_REMOTE}\n"
    )


def register_init_command(app: typer.Typer) -> None:
    @app.command("init")
    def init_command(
        output: Annotated[
            Path,
            typer.Option(
                "--output",
                help="Chemin du fichier de configuration à créer.",
            ),
        ] = DEFAULT_OUTPUT,
        force: Annotated[
            bool,
            typer.Option(
                "--force",
                help="Écrase le fichier s'il existe déjà.",
            ),
        ] = False,
        provider: Annotated[
            str,
            typer.Option(
                "--provider",
                help="Provider à écrire dans la configuration initiale.",
            ),
        ] = DEFAULT_PROVIDER,
        model: Annotated[
            str,
            typer.Option(
                "--model",
                help="Modèle à écrire dans la configuration initiale.",
            ),
        ] = DEFAULT_MODEL,
        lang: Annotated[
            str,
            typer.Option(
                "--lang",
                help="Langue par défaut à écrire dans la configuration initiale.",
            ),
        ] = DEFAULT_LANGUAGE,
        base_url: Annotated[
            str,
            typer.Option(
                "--base-url",
                help="URL du backend à écrire dans la configuration initiale.",
            ),
        ] = DEFAULT_BASE_URL,
        push: Annotated[
            bool,
            typer.Option(
                "--push/--no-push",
                help="Valeur initiale de push_after_commit.",
            ),
        ] = DEFAULT_PUSH_AFTER_COMMIT,
    ) -> None:
        validated_provider = _validate_provider(provider)
        validated_lang = _validate_language(lang)
        normalized_model = _validate_non_empty(model, "Model")
        normalized_base_url = _validate_non_empty(base_url, "Base URL")

        if output.exists() and not force:
            typer.secho(
                f"Erreur : le fichier existe déjà : {output}",
                fg=typer.colors.RED,
                err=True,
            )
            raise typer.Exit(code=2)

        content = _build_init_config_text(
            provider=validated_provider,
            model=normalized_model,
            language=validated_lang,
            base_url=normalized_base_url,
            push_after_commit=push,
        )

        output.write_text(content, encoding="utf-8")

        typer.secho(
            f"Fichier de configuration créé : {output}",
            fg=typer.colors.GREEN,
        )
        typer.echo("")
        typer.echo("Valeurs initiales :")
        typer.echo(f"- provider : {validated_provider}")
        typer.echo(f"- model : {normalized_model}")
        typer.echo(f"- language : {validated_lang}")
        typer.echo(f"- base_url : {normalized_base_url}")
        typer.echo(f"- push_after_commit : {push}")
        typer.echo("")
        typer.echo("Étapes suivantes :")
        typer.echo("1. Ajustez git-ai.yaml si nécessaire.")
        typer.echo("2. Ajoutez vos fichiers avec git add.")
        typer.echo("3. Lancez `git-ai commit --dry-run`.")